### ISSUE TITLE
Kartagener syndrome / primary ciliary dyskinesia

### ISSUE THREAD

**Issue by cmungall** [monarch-initiative/mondo#209]
We treat KS as a subclass of PCD. 

Orphanet had a distinct class for KS
https://www.ebi.ac.uk/ols/ontologies/ordo/terms?iri=http%3A%2F%2Fwww.orpha.net%2FORDO%2FOrphanet_98861

but this is deprecated in favor of the broader PCD

should these be merged?

**Comment by cmungall** [comment]
current

        is_a MONDO:0016575 ! primary ciliary dyskinesia *** 
         is_a MONDO:0000260 ! Kartagener syndrome
         is_a MONDO:0008984 ! ciliary discoordination due to random ciliary orientation
         is_a MONDO:0008985 ! ciliary dyskinesia with transposition of ciliary microtubules
         is_a MONDO:0009449 ! ciliary dyskinesia with defective radial spokes
         is_a MONDO:0009450 ! ciliary dyskinesia with excessively long cilia
         is_a MONDO:0009484 ! primary ciliary dyskinesia 1
         is_a MONDO:0010517 ! ciliary dyskinesia, primary, 36, X-linked; CILD36
         is_a MONDO:0011718 ! primary ciliary dyskinesia 2
         is_a MONDO:0012085 ! primary ciliary dyskinesia 3
         is_a MONDO:0012087 ! primary ciliary dyskinesia 4
         is_a MONDO:0012088 ! primary ciliary dyskinesia 5
         is_a MONDO:0012571 ! primary ciliary dyskinesia 6
         is_a MONDO:0012748 ! primary ciliary dyskinesia 7
         is_a MONDO:0012844 ! primary ciliary dyskinesia 8
         is_a MONDO:0012906 ! primary ciliary dyskinesia 9
         is_a MONDO:0012918 ! primary ciliary dyskinesia 10
         is_a MONDO:0012978 ! primary ciliary dyskinesia 11
         is_a MONDO:0012979 ! primary ciliary dyskinesia 12
         is_a MONDO:0013174 ! primary ciliary dyskinesia 13
         is_a MONDO:0013434 ! primary ciliary dyskinesia 14
         is_a MONDO:0013435 ! primary ciliary dyskinesia 15
         is_a MONDO:0013525 ! primary ciliary dyskinesia 16
         is_a MONDO:0013854 ! primary ciliary dyskinesia 17
         is_a MONDO:0013940 ! primary ciliary dyskinesia 18
         is_a MONDO:0013979 ! primary ciliary dyskinesia 19
         is_a MONDO:0014030 ! primary ciliary dyskinesia 20
         is_a MONDO:0014123 ! primary ciliary dyskinesia 21
         is_a MONDO:0014192 ! primary ciliary dyskinesia 22
         is_a MONDO:0014193 ! primary ciliary dyskinesia 23
         is_a MONDO:0014202 ! primary ciliary dyskinesia 24
         is_a MONDO:0014203 ! primary ciliary dyskinesia 25
         is_a MONDO:0014211 ! primary ciliary dyskinesia 26
         is_a MONDO:0014215 ! primary ciliary dyskinesia 27
         is_a MONDO:0014216 ! primary ciliary dyskinesia 28
         is_a MONDO:0014378 ! primary ciliary dyskinesia 29
         is_a MONDO:0014465 ! primary ciliary dyskinesia 30
         is_a MONDO:0014610 ! lethal fetal brain malformation-duodenal atresia-bilateral renal hypoplasia syndrome
         is_a MONDO:0014657 ! primary ciliary dyskinesia 32
         is_a MONDO:0014750 ! primary ciliary dyskinesia 33
         is_a MONDO:0014909 ! primary ciliary dyskinesia 34
         is_a MONDO:0014910 ! primary ciliary dyskinesia 35

**Comment by cmungall** [comment]
Give it a shot but check the diff before committing!

**Comment by nicolevasilevsky** [comment]
It is telling me that I don't have a new.obo file

BICB119:~ vasilevs$ cd git/mondo-build/src/ontology/
BICB119:ontology vasilevs$ ls
MONDO_GO_Phenologs.ipynb	mirror
Makefile			modules
Makefile~			mondo-edit.obo
README-editors.md		mondo-idranges.owl
catalog-v001.xml		prefixes.yaml
imports				reports
BICB119:ontology vasilevs$ owltools mondo-edit.obo  --obsolete-replace MONDO:0000260 mondo:0016575 --assert-inferred-subclass-axioms --markIsInferred --removeRedundant -o -f obo new.obo
2018-05-21 17:33:58,443 ERROR (CommandRunner:4384) could not parse:--obsolete-replace
org.semanticweb.owlapi.io.OWLOntologyCreationIOException: /Users/vasilevs/git/mondo-build/src/ontology/--obsolete-replace (No such file or directory)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:207)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.actualParse(OWLOntologyManagerImpl.java:1098)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:1054)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:957)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyManagerImpl.loadOntology(OWLOntologyManagerImpl.java:913)
	at owltools.io.ParserWrapper.parseOWL(ParserWrapper.java:163)
	at owltools.io.ParserWrapper.parseOWL(ParserWrapper.java:150)
	at owltools.io.ParserWrapper.parse(ParserWrapper.java:132)
	at owltools.cli.CommandRunner.runSingleIteration(CommandRunner.java:4372)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:76)
	at owltools.cli.CommandRunnerBase.run(CommandRunnerBase.java:68)
	at owltools.cli.CommandLineInterface.main(CommandLineInterface.java:12)
Caused by: java.io.FileNotFoundException: /Users/vasilevs/git/mondo-build/src/ontology/--obsolete-replace (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at sun.net.www.protocol.file.FileURLConnection.connect(FileURLConnection.java:90)
	at sun.net.www.protocol.file.FileURLConnection.getInputStream(FileURLConnection.java:188)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStreamFromContentEncoding(AbstractOWLParser.java:165)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputStream(AbstractOWLParser.java:127)
	at org.semanticweb.owlapi.io.AbstractOWLParser.getInputSource(AbstractOWLParser.java:232)
	at org.semanticweb.owlapi.rdf.rdfxml.parser.RDFXMLParser.parse(RDFXMLParser.java:72)
	at uk.ac.manchester.cs.owl.owlapi.OWLOntologyFactoryImpl.loadOWLOntology(OWLOntologyFactoryImpl.java:197)
	... 11 more
BICB119:ontology vasilevs$ diff mondo-edit.obo new.obo
diff: new.obo: No such file or directory
BICB119:ontology vasilevs$

**Comment by cmungall** [comment]
The first command failed. You'll need to update yr owltools or use the
docket container

**Comment by nicolevasilevsky** [comment]
Can you tell me how to do either of those things?

**Comment by cmungall** [comment]
yep look for me on gitter
