### ISSUE TITLE
bug in mondo.json

### ISSUE THREAD

**Issue by sabrinatoro** [monarch-initiative/mondo#6222]
(from @pnrobinson , on slack)

mondo.json appears to have a bug
When trying to load it we get this
/Users/robinp/Downloads/l4ci/data/mondo.json
org.monarchinitiative.phenol.base.PhenolRuntimeException: Error loading JSON
        at [org.monarchinitiative.phenol.io](http://org.monarchinitiative.phenol.io/).OntologyLoader.loadGraphDocument(OntologyLoader.java:109)
        at [org.monarchinitiative.phenol.io](http://org.monarchinitiative.phenol.io/).OntologyLoader.loadGraphDocument(OntologyLoader.java:90)
        at [org.monarchinitiative.phenol.io](http://org.monarchinitiative.phenol.io/).OntologyLoader.loadOntology(OntologyLoader.java:43)
        at [org.monarchinitiative.l4ci.core.io](http://org.monarchinitiative.l4ci.core.io/).HPOParser.parse(HPOParser.java:32)
        at [org.monarchinitiative.l4ci.core.io](http://org.monarchinitiative.l4ci.core.io/).HPOParser.<init>(HPOParser.java:20)
        at org.monarchinitiative.l4ci.cli.cmd.BenchmarkCommand.loadOntologies(BenchmarkCommand.java:298)
        at org.monarchinitiative.l4ci.cli.cmd.GeneAnalysisCommand.call(GeneAnalysisCommand.java:80)
        at org.monarchinitiative.l4ci.cli.cmd.GeneAnalysisCommand.call(GeneAnalysisCommand.java:40)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1933)
        at picocli.CommandLine.access$1200(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2332)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2326)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2291)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2159)
        at picocli.CommandLine.execute(CommandLine.java:2058)
        at org.monarchinitiative.l4ci.cli.Main.main(Main.java:29)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:108)
        at org.springframework.boot.loader.Launcher.launch(Launcher.java:58)
        at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:88)
Caused by: com.fasterxml.jackson.databind.exc.ValueInstantiationException: Cannot construct instance of `org.geneontology.obographs.core.model.axiom.LogicalDefinitionAxiom`, problem: `java.lang.NullPointerException`
 at [Source: (BufferedInputStream); line: 1835151, column: 5] (through reference chain: org.geneontology.obographs.core.model.GraphDocument$Builder["graphs"]->java.util.ArrayList[0]->org.geneontology.obographs.core.model.Graph$Json["logicalDefinitionAxioms"]->java.util.ArrayList[309])
        at com.fasterxml.jackson.databind.exc.ValueInstantiationException.from(ValueInstantiationException.java:47)
        at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:2047)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.wrapAsJsonMappingException(StdValueInstantiator.java:587)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.rewrapCtorProblem(StdValueInstantiator.java:610)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator._createUsingDelegate(StdValueInstantiator.java:647)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createUsingDelegate(StdValueInstantiator.java:306)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1397)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:313)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer._deserializeOther(BeanDeserializer.java:214)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:186)
        at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.deserializeFromObjectUsingNonDefault(BeanDeserializerBase.java:1398)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:351)
        at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:184)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer._deserializeFromArray(CollectionDeserializer.java:355)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:244)
        at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:28)
        at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeSetAndReturn(MethodProperty.java:158)
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.vanillaDeserialize(BuilderBasedDeserializer.java:293)
        at com.fasterxml.jackson.databind.deser.BuilderBasedDeserializer.deserialize(BuilderBasedDeserializer.java:217)
        at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:322)
        at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674)
        at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3666)
        at [org.monarchinitiative.phenol.io](http://org.monarchinitiative.phenol.io/).obographs.OboGraphDocumentLoader.loadJson(OboGraphDocumentLoader.java:35)
        at [org.monarchinitiative.phenol.io](http://org.monarchinitiative.phenol.io/).OntologyLoader.loadGraphDocument(OntologyLoader.java:107)
        ... 21 more
Caused by: java.lang.NullPointerException
        at com.google.common.base.Preconditions.checkNotNull(Preconditions.java:782)
        at com.google.common.collect.ImmutableCollection$ArrayBasedBuilder.add(ImmutableCollection.java:479)
        at com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:743)
        at com.google.common.collect.ImmutableList$Builder.add(ImmutableList.java:719)
        at com.google.common.collect.ImmutableCollection$Builder.addAll(ImmutableCollection.java:419)
        at com.google.common.collect.ImmutableCollection$ArrayBasedBuilder.addAll(ImmutableCollection.java:502)
        at com.google.common.collect.ImmutableList$Builder.addAll(ImmutableList.java:758)
        at org.geneontology.obographs.core.model.axiom.LogicalDefinitionAxiom$Builder.addAllRestrictions(LogicalDefinitionAxiom.java:462)
        at org.geneontology.obographs.core.model.axiom.LogicalDefinitionAxiom.fromJson(LogicalDefinitionAxiom.java:260)
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104)
        at java.base/java.lang.reflect.Method.invoke(Method.java:578)
        at com.fasterxml.jackson.databind.introspect.AnnotatedMethod.call1(AnnotatedMethod.java:109)
        at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator._createUsingDelegate(StdValueInstantiator.java:631)
        ... 46 more

I think the error is coming from obographs although the exception is thrown from phenol

**Comment by matentzn** [comment]
Closing in favour of https://github.com/geneontology/obographs/issues/96
